spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 123456
      # connect的版本6.x 以上 com.mysql.cj.jdbc.Driver
      # 版本5.x 以下 com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
      # 指定nacos server的ip和端口
        server-addr: localhost:8848
        namespace: de1f60d3-097f-4421-b3b2-cf1bad41656d #dev
        cluster-name: NJ
        metadata:
          instance: xxx
          key: value
          version: v1
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        input:
          destination: stream-test-topic
          group: bind-group # 注意需要一个group，否则启动失败，如果不是rocketMQ则可以留空
        my-input:
          destination: stream-my-topic
          group: my-group
        my-tx-input:
           destination: add-bonus
           group: consumer-group
  application:
  # 服务名称，不要用_，尽量使用-
    name: user-center
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
    # 抽样率，默认是0.1, 配置1.0，则所有的请求都会上报给zipkin
      probability: 1.0
server:
  port: 8088

logging:
  level:
    com.stt: debug
    com.alibaba.nacos: error
    org.springframework.cloud.sleuth: debug
rocketmq:
  name-server: localhost:9876

jwt:
  secret: aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always