version: '3.1'
services:
  myshop-service-user-provider:
    image: 192.168.119.134:5000/myshop-service-user-provider:v1.0.0
    container_name: myshop-service-user-provider
    ports:
      - 8501:8501
      - 22222:22222
      - 20881:20881

networks:
  default:
    external:
      name: dubbo
      # 由于dubbo的调用必须在同一个局域网内，
      # Network dubbo declared as external, but could not be found.
      # Please create the network manually using `docker network create dubbo` and try again. 需要手动创建网络