spring:
  application:
    name: server-consumer-ribbon
  zipkin:
    base-url: http://localhost:9411

  boot:
    admin:
      client:
        url: http://localhost:8084

server:
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/