spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 123456
      # connect的版本6.x 以上 com.mysql.cj.jdbc.Driver
      # 版本5.x 以下 com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
      # 指定nacos server的ip和端口
        server-addr: localhost:8848
        namespace: de1f60d3-097f-4421-b3b2-cf1bad41656d #dev
        cluster-name: BEIJING
    sentinel:
      transport:
      # 指定sentinel控制台的地址
        dashboard: localhost:8080
      filter:
      # 关闭sentinel 对springMVC的保护，防止测试sentinel API的干扰
#        enabled: false
        enabled: true
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
        bindings: # 注意在rocketmq中的bindins
          tx-add-bonus-output:
            producer:
              transactional: true # 说明是事务消息
              group: tx-add-bonus-group # 设置group
      bindings:
        output:
        # 用于指定topic
          destination: stream-test-topic
        my-output:
          destination: stream-my-topic
        tx-add-bonus-output:
          destination: add-bonus
  zipkin:
    base-url: http://localhost:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
    # 抽样率，默认是0.1, 配置1.0，则所有的请求都会上报给zipkin
      probability: 1.0
  main:
    allow-bean-definition-overriding: true
  application:
  # 服务名称，不要用_，尽量使用-
      name: content-center

server:
  port: 8010


ribbon:
  eager-load:
    enabled: true
    clients: user-center
    # 要支持多个，使用,号分隔

logging:
  level:
    # feign的日志级别是建立在log日志的debug级别上的，如果是info则不会打印日志
    com.stt.contentcenter.feign.client.UserCenterFeignClient: debug
    com.alibaba.nacos: error
    com.stt.contentcenter.dao.content: debug
#feign:
#  client:
#    config:
#    # 调用的微服务的名称
#      user-center:
#        loggerLevel: full

feign:
  client:
    config:
    # 全局配置
      default:
        loggerLevel: full
        requestInterceptors:
          - com.stt.contentcenter.feign.interceptor.TokenRelayRequestInterceptor
  httpclient:
  # 使用apache httpclient 而不是默认的urlConnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign的单个路径的最大连接数
    max-connections-per-route: 50
  sentinel:
  # 给feign整合sentinel
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
rocketmq:
  name-server: localhost:9876
  producer:
    # 必须指定group
    group: test-group

#resttemplate:
#  sentinel:
#  # 关闭SentinelRestTemplate注解
#    enabled: false


#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

jwt:
  secret: aaabbbcccdddeeefffggghhhiiijjjkkklllmmmnnnooopppqqqrrrsssttt
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600

mybatis:
  configuration:
    map-underscore-to-camel-case: true