server:
  port: 8601 # 服务提供者从8501开始，服务消费者从8601开始

spring:
  application:
    name: itoken-web-admin
  boot:
    admin:
      client:
        url: http://localhost:8084
  zipkin:
    base-url: http://localhost:9411
  thymeleaf:
    cache: false # 开发时关闭缓存,不然没法看到实时页面
    mode: LEGACYHTML5 # 用非严格的 HTML 需要添加 nekohtml 依赖
    encoding: UTF-8
    servlet:
      content-type: text/html


feign:
  hystrix:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info