spring:
  boot:
    admin:
      client:
        url: http://192.168.119.132:8084

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info